// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxcBiFPmqrsu5UQR7AGWbzJcDbFt3Bzw',
    appId: '1:363332554737:web:8fd6a2100329adfe357e50',
    messagingSenderId: '363332554737',
    projectId: 'care-bus',
    authDomain: 'care-bus.firebaseapp.com',
    storageBucket: 'care-bus.appspot.com',
    measurementId: 'G-56KXVQGWK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQaOAVFdRsiRu7YtQqny-W35X-o3goKk',
    appId: '1:363332554737:android:7634b27671432252357e50',
    messagingSenderId: '363332554737',
    projectId: 'care-bus',
    storageBucket: 'care-bus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLon6xKSkLmJAa8ivG3zFvMbvNwgLygbc',
    appId: '1:363332554737:ios:b4ab3ae152d95aea357e50',
    messagingSenderId: '363332554737',
    projectId: 'care-bus',
    storageBucket: 'care-bus.appspot.com',
    iosBundleId: 'com.example.careBus',
  );
}
